# Netlify configuration for optimal performance

[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 8888
  autoLaunch = true

# Asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Cache control for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # Temporarily commenting out CSP to debug
    # Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.auth0.com https://*.contentful.com https://cdn.jsdelivr.net https://unpkg.com https://cdnjs.cloudflare.com https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://unpkg.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https://*.contentful.com https://*.auth0.com https://www.google-analytics.com https://www.googletagmanager.com blob:; connect-src 'self' https://*.auth0.com https://*.contentful.com https://www.google-analytics.com https://www.googletagmanager.com https://*.netlify.app wss://*.netlify.app; frame-src 'self' https://*.auth0.com https://www.youtube.com; media-src 'self' https://*.contentful.com; worker-src 'self' blob:;"

# Cache control for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Special SPA configuration
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Brotli compression
[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--no-audit"
  # Temporarily disable CommandBar plugin
  DISABLE_PLUGIN_COMMANDBAR = "true"

# Edge functions for global distribution
[[edge_functions]]
  function = "country-detect"
  path = "/*"

# Correct CommandBar Plugin syntax
# Comment out the CommandBar plugin for now until the build is stable
# [[plugins]]
#   package = "@commandbar/netlify-plugin-commandbar"

[functions]
  node_bundler = "esbuild"

[functions.api]
  included_files = ["netlify/functions/utils/**"] 